//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppFunkoPop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FunkoPopDDBBEntities : DbContext
    {
        public FunkoPopDDBBEntities()
            : base("name=FunkoPopDDBBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CARRITO> CARRITOes { get; set; }
        public virtual DbSet<CARRITOPRODUCTO> CARRITOPRODUCTOes { get; set; }
        public virtual DbSet<ESTADO_ENVIO> ESTADO_ENVIO { get; set; }
        public virtual DbSet<PEDIDO> PEDIDOes { get; set; }
        public virtual DbSet<PEDIDOPRODUCTO> PEDIDOPRODUCTOes { get; set; }
        public virtual DbSet<PRODUCTO> PRODUCTOes { get; set; }
        public virtual DbSet<PROVEEDOR> PROVEEDORs { get; set; }
        public virtual DbSet<ROL> ROLs { get; set; }
        public virtual DbSet<USUARIO> USUARIOs { get; set; }
    }
}
