//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppFunkoPop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PEDIDO()
        {
            this.PEDIDOPRODUCTOes = new HashSet<PEDIDOPRODUCTO>();
        }
    
        public int PEDIDO_ID { get; set; }
        public int USUARIO_ID { get; set; }
        public decimal PRECIO_TOTAL { get; set; }
        public string INFO_PAGO { get; set; }
        public int ESTADO_ENVIO { get; set; }
    
        public virtual ESTADO_ENVIO ESTADO_ENVIO1 { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PEDIDOPRODUCTO> PEDIDOPRODUCTOes { get; set; }
    }
}
