//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppFunkoPop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PROVEEDOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROVEEDOR()
        {
            this.PRODUCTOes = new HashSet<PRODUCTO>();
        }
    
        public int PROVEEDOR_ID { get; set; }
        [Display(Name = "Nombre Proveedor")]
        [Required(ErrorMessage = "Es necesario introducir el nombre ")]
        public string NOMBRE_PROV { get; set; }
        [Display(Name = "Telefono")]
        [Required(ErrorMessage = "Es necesario introducir el teléfono ")]
        public int TLFN_PROV { get; set; }
        [Display(Name = "Email")]
        [Required(ErrorMessage = "Es necesario introducir el email ")]
        public string EMAIL_PROV { get; set; }
        [Display(Name = "Descripción Proveedor")]
        public string DESCRIPCION_PROV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTO> PRODUCTOes { get; set; }
    }
}
