//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppFunkoPop.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Account {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Account() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppFunkoPop.Resources.Account", typeof(Account).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Surname.
        /// </summary>
        public static string apellidos {
            get {
                return ResourceManager.GetString("apellidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        public static string borrar {
            get {
                return ResourceManager.GetString("borrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a City.
        /// </summary>
        public static string ciudad {
            get {
                return ResourceManager.GetString("ciudad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Postal code.
        /// </summary>
        public static string codigoPostal {
            get {
                return ResourceManager.GetString("codigoPostal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create new account.
        /// </summary>
        public static string crearNuevaCuenta {
            get {
                return ResourceManager.GetString("crearNuevaCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Account.
        /// </summary>
        public static string direccion {
            get {
                return ResourceManager.GetString("direccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a email.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log in.
        /// </summary>
        public static string entrar {
            get {
                return ResourceManager.GetString("entrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log in.
        /// </summary>
        public static string iniciarSesion {
            get {
                return ResourceManager.GetString("iniciarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        public static string nombre {
            get {
                return ResourceManager.GetString("nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Country.
        /// </summary>
        public static string pais {
            get {
                return ResourceManager.GetString("pais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string passwd {
            get {
                return ResourceManager.GetString("passwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign in.
        /// </summary>
        public static string registrarse {
            get {
                return ResourceManager.GetString("registrarse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Phone number.
        /// </summary>
        public static string tlfn {
            get {
                return ResourceManager.GetString("tlfn", resourceCulture);
            }
        }
    }
}
