//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppFunkoPop.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Carrito {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Carrito() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppFunkoPop.Resources.Carrito", typeof(Carrito).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add unit.
        /// </summary>
        public static string añadirUnidad {
            get {
                return ResourceManager.GetString("añadirUnidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string apellidos {
            get {
                return ResourceManager.GetString("apellidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string borrar {
            get {
                return ResourceManager.GetString("borrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete product.
        /// </summary>
        public static string borrarProducto {
            get {
                return ResourceManager.GetString("borrarProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete unit.
        /// </summary>
        public static string borrarUnidad {
            get {
                return ResourceManager.GetString("borrarUnidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string cambiarContras {
            get {
                return ResourceManager.GetString("cambiarContras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string cambiarContrasena {
            get {
                return ResourceManager.GetString("cambiarContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string ciudad {
            get {
                return ResourceManager.GetString("ciudad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal code.
        /// </summary>
        public static string codigoPostal {
            get {
                return ResourceManager.GetString("codigoPostal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        public static string confContNueva {
            get {
                return ResourceManager.GetString("confContNueva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password.
        /// </summary>
        public static string contAntigua {
            get {
                return ResourceManager.GetString("contAntigua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string contNueva {
            get {
                return ResourceManager.GetString("contNueva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adress.
        /// </summary>
        public static string direccion {
            get {
                return ResourceManager.GetString("direccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string entrar {
            get {
                return ResourceManager.GetString("entrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage my account.
        /// </summary>
        public static string gestionarMisDatos {
            get {
                return ResourceManager.GetString("gestionarMisDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User management.
        /// </summary>
        public static string gestionUsuarios {
            get {
                return ResourceManager.GetString("gestionUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string imagen {
            get {
                return ResourceManager.GetString("imagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of products in the cart.
        /// </summary>
        public static string listadoProductos {
            get {
                return ResourceManager.GetString("listadoProductos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View my cart.
        /// </summary>
        public static string miCarrito {
            get {
                return ResourceManager.GetString("miCarrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View my orders.
        /// </summary>
        public static string misPedidos {
            get {
                return ResourceManager.GetString("misPedidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string nombre {
            get {
                return ResourceManager.GetString("nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new account.
        /// </summary>
        public static string nuevaCuenta {
            get {
                return ResourceManager.GetString("nuevaCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string pais {
            get {
                return ResourceManager.GetString("pais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User control panel.
        /// </summary>
        public static string panelControlUsuarios {
            get {
                return ResourceManager.GetString("panelControlUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string precio {
            get {
                return ResourceManager.GetString("precio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string precioTotal {
            get {
                return ResourceManager.GetString("precioTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price by unit.
        /// </summary>
        public static string precioUnidad {
            get {
                return ResourceManager.GetString("precioUnidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These are the products currently selected.
        /// </summary>
        public static string presentacionListado {
            get {
                return ResourceManager.GetString("presentacionListado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿What do you want to do?.
        /// </summary>
        public static string queQuieresHacer {
            get {
                return ResourceManager.GetString("queQuieresHacer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make an order.
        /// </summary>
        public static string realizarPedido {
            get {
                return ResourceManager.GetString("realizarPedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string telefono {
            get {
                return ResourceManager.GetString("telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        public static string unidades {
            get {
                return ResourceManager.GetString("unidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units avaible.
        /// </summary>
        public static string unidadesDisponibles {
            get {
                return ResourceManager.GetString("unidadesDisponibles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty cart.
        /// </summary>
        public static string vaciarCarrito {
            get {
                return ResourceManager.GetString("vaciarCarrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See order.
        /// </summary>
        public static string VerPedidoUnico {
            get {
                return ResourceManager.GetString("VerPedidoUnico", resourceCulture);
            }
        }
    }
}
