//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppFunkoPop.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Shared {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Shared() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppFunkoPop.Resources.Shared", typeof(Shared).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal advice.
        /// </summary>
        public static string avisoLegal {
            get {
                return ResourceManager.GetString("avisoLegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wellcome admin.
        /// </summary>
        public static string bienvenidoAdmin {
            get {
                return ResourceManager.GetString("bienvenidoAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        public static string bloqueado {
            get {
                return ResourceManager.GetString("bloqueado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart.
        /// </summary>
        public static string carrito {
            get {
                return ResourceManager.GetString("carrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalogue.
        /// </summary>
        public static string catalogo {
            get {
                return ResourceManager.GetString("catalogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string cerrarSesion {
            get {
                return ResourceManager.GetString("cerrarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        public static string contactanos {
            get {
                return ResourceManager.GetString("contactanos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conctact us.
        /// </summary>
        public static string contacto {
            get {
                return ResourceManager.GetString("contacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account id blocked, try it again later..
        /// </summary>
        public static string cuentaBloqueada {
            get {
                return ResourceManager.GetString("cuentaBloqueada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check out our featured products!.
        /// </summary>
        public static string destacado {
            get {
                return ResourceManager.GetString("destacado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where we are.
        /// </summary>
        public static string dondeEstamos {
            get {
                return ResourceManager.GetString("dondeEstamos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Episode 3.
        /// </summary>
        public static string episodio3 {
            get {
                return ResourceManager.GetString("episodio3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error procesing the reguest.
        /// </summary>
        public static string errorSolicitud {
            get {
                return ResourceManager.GetString("errorSolicitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        public static string español {
            get {
                return ResourceManager.GetString("español", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game of Throne.
        /// </summary>
        public static string got {
            get {
                return ResourceManager.GetString("got", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string hola {
            get {
                return ResourceManager.GetString("hola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string ingles {
            get {
                return ResourceManager.GetString("ingles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string iniciarSesion {
            get {
                return ResourceManager.GetString("iniciarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string inicio {
            get {
                return ResourceManager.GetString("inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The North.
        /// </summary>
        public static string norte {
            get {
                return ResourceManager.GetString("norte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string otros {
            get {
                return ResourceManager.GetString("otros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy policy.
        /// </summary>
        public static string politicaPrivacidad {
            get {
                return ResourceManager.GetString("politicaPrivacidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string registrarse {
            get {
                return ResourceManager.GetString("registrarse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return of the Jedi.
        /// </summary>
        public static string retorno {
            get {
                return ResourceManager.GetString("retorno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string todos {
            get {
                return ResourceManager.GetString("todos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last Jedi.
        /// </summary>
        public static string ultimo {
            get {
                return ResourceManager.GetString("ultimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avengers.
        /// </summary>
        public static string vengadores {
            get {
                return ResourceManager.GetString("vengadores", resourceCulture);
            }
        }
    }
}
